import { Exercise } from '@/types'

export const EXERCISES: Exercise[] = [
  // CHEST
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    slug: 'barbell-bench-press',
    muscle_group: 'chest',
    secondary_muscles: ['triceps', 'front_deltoid'],
    equipment_required: ['Barbell', 'Flat Bench', 'Weight Plates'],
    exercise_type: 'compound',
    difficulty: 'intermediate',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Lie flat on the bench, feet firmly on the floor.', 'Grip the bar slightly wider than shoulder-width.', 'Lower the bar to mid-chest in a controlled arc.', 'Press the bar back up explosively.'],
    common_mistakes: ['Bouncing the bar off the chest.', 'Flaring elbows too wide.', 'Lifting glutes off the bench.'],
    default_sets: 4,
    default_reps: '6-10',
    rest_time_seconds: 120,
    calories_per_set: 22,
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    slug: 'dumbbell-bench-press',
    muscle_group: 'chest',
    secondary_muscles: ['triceps', 'front_deltoid'],
    equipment_required: ['Dumbbells', 'Flat Bench'],
    exercise_type: 'compound',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Hold a dumbbell in each hand and lie on a flat bench.', 'Start with dumbbells at chest level, elbows at 90°.', 'Press the dumbbells up until arms are extended.', 'Slowly lower back to starting position.'],
    common_mistakes: ['Using too much weight.', 'Not achieving full range of motion.'],
    default_sets: 3,
    default_reps: '10-12',
    rest_time_seconds: 90,
    calories_per_set: 18,
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    muscle_group: 'chest',
    secondary_muscles: ['front_deltoid', 'triceps'],
    equipment_required: ['Dumbbells', 'Incline Bench'],
    exercise_type: 'compound',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Set the bench to 30-45° incline.', 'Hold dumbbells at chest level.', 'Press up and slightly inward.', 'Lower slowly with control.'],
    common_mistakes: ['Setting incline too high.', 'Partial range of motion.'],
    default_sets: 3,
    default_reps: '10-12',
    rest_time_seconds: 90,
    calories_per_set: 18,
  },
  {
    id: 'chest-press-machine',
    name: 'Chest Press Machine',
    slug: 'chest-press-machine',
    muscle_group: 'chest',
    secondary_muscles: ['triceps'],
    equipment_required: ['Chest Press Machine'],
    exercise_type: 'compound',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Adjust seat so handles align with mid-chest.', 'Press forward until arms extend.', 'Return slowly without dropping the stack.'],
    common_mistakes: ['Not adjusting seat height.', 'Rushing the eccentric phase.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 75,
    calories_per_set: 15,
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    slug: 'push-up',
    muscle_group: 'chest',
    secondary_muscles: ['triceps', 'front_deltoid', 'core'],
    equipment_required: [],
    exercise_type: 'bodyweight',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Start in a high plank, hands shoulder-width apart.', 'Lower your chest to the floor, elbows at 45°.', 'Push back up to starting position.'],
    common_mistakes: ['Sagging hips.', 'Head drooping.'],
    default_sets: 3,
    default_reps: '15-20',
    rest_time_seconds: 60,
    calories_per_set: 12,
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    slug: 'dumbbell-fly',
    muscle_group: 'chest',
    secondary_muscles: ['front_deltoid'],
    equipment_required: ['Dumbbells', 'Flat Bench'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Lie on flat bench, dumbbells above chest, palms facing.', 'Lower in an arc until you feel a stretch.', 'Bring back up squeezing the chest at the top.'],
    common_mistakes: ['Bending arms too much.', 'Going too heavy.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 75,
    calories_per_set: 14,
  },
  // BACK
  {
    id: 'barbell-row',
    name: 'Barbell Bent-Over Row',
    slug: 'barbell-bent-over-row',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'rear_deltoid', 'core'],
    equipment_required: ['Barbell', 'Weight Plates'],
    exercise_type: 'compound',
    difficulty: 'intermediate',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Hinge forward at hips ~45°, overhand grip.', 'Pull bar to lower chest, leading with elbows.', 'Lower with control to full extension.'],
    common_mistakes: ['Rounding the lower back.', 'Using momentum.'],
    default_sets: 4,
    default_reps: '6-10',
    rest_time_seconds: 120,
    calories_per_set: 24,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'rear_deltoid'],
    equipment_required: ['Lat Pulldown Machine'],
    exercise_type: 'compound',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Sit and secure thighs under the pad.', 'Pull the bar to your upper chest.', 'Let bar travel back up with control.'],
    common_mistakes: ['Pulling behind the neck.', 'Using momentum.'],
    default_sets: 4,
    default_reps: '8-12',
    rest_time_seconds: 90,
    calories_per_set: 20,
  },
  {
    id: 'dumbbell-row',
    name: 'Single-Arm Dumbbell Row',
    slug: 'single-arm-dumbbell-row',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'rear_deltoid'],
    equipment_required: ['Dumbbells', 'Flat Bench'],
    exercise_type: 'compound',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Place knee and hand on bench for support.', 'Pull the dumbbell toward your hip, elbow leading.', 'Lower with control to full extension.'],
    common_mistakes: ['Rotating the torso too much.', 'Pulling to shoulder level.'],
    default_sets: 3,
    default_reps: '10-12',
    rest_time_seconds: 90,
    calories_per_set: 17,
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    slug: 'pull-up',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'rear_deltoid'],
    equipment_required: ['Pull-up Bar'],
    exercise_type: 'bodyweight',
    difficulty: 'intermediate',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Hang from bar with overhand grip, wider than shoulders.', 'Pull chin over the bar, leading with chest.', 'Lower slowly with full arm extension.'],
    common_mistakes: ['Kipping.', 'Not achieving chin over bar.'],
    default_sets: 3,
    default_reps: '6-12',
    rest_time_seconds: 90,
    calories_per_set: 16,
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    slug: 'seated-cable-row',
    muscle_group: 'back',
    secondary_muscles: ['biceps', 'rear_deltoid'],
    equipment_required: ['Cable Machine'],
    exercise_type: 'compound',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Sit at the cable row machine.', 'Pull the handle to your abdomen, driving elbows back.', 'Return to full extension with control.'],
    common_mistakes: ['Hunching forward.', 'Using back swing.'],
    default_sets: 3,
    default_reps: '10-12',
    rest_time_seconds: 90,
    calories_per_set: 18,
  },
  // SHOULDERS
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    slug: 'dumbbell-shoulder-press',
    muscle_group: 'shoulders',
    secondary_muscles: ['triceps', 'upper_traps'],
    equipment_required: ['Dumbbells'],
    exercise_type: 'compound',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Sit upright, dumbbells at shoulder height.', 'Press dumbbells overhead until arms are extended.', 'Lower back to shoulder height with control.'],
    common_mistakes: ['Arching lower back.', 'Pressing forward instead of up.'],
    default_sets: 3,
    default_reps: '8-12',
    rest_time_seconds: 90,
    calories_per_set: 17,
  },
  {
    id: 'lateral-raise',
    name: 'Dumbbell Lateral Raise',
    slug: 'dumbbell-lateral-raise',
    muscle_group: 'shoulders',
    secondary_muscles: [],
    equipment_required: ['Dumbbells'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Stand with dumbbells at sides.', 'Raise arms out to the sides until parallel to floor.', 'Lower slowly with control.'],
    common_mistakes: ['Using momentum.', 'Shrugging shoulders.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 60,
    calories_per_set: 12,
  },
  // LEGS
  {
    id: 'barbell-squat',
    name: 'Barbell Back Squat',
    slug: 'barbell-back-squat',
    muscle_group: 'legs',
    secondary_muscles: ['glutes', 'hamstrings', 'core'],
    equipment_required: ['Barbell', 'Weight Plates'],
    exercise_type: 'compound',
    difficulty: 'intermediate',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Bar on upper traps, feet shoulder-width.', 'Descend until thighs are parallel.', 'Drive through heels to stand.'],
    common_mistakes: ['Knees caving inward.', 'Heels rising.', 'Rounding lower back.'],
    default_sets: 4,
    default_reps: '6-10',
    rest_time_seconds: 150,
    calories_per_set: 30,
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    slug: 'goblet-squat',
    muscle_group: 'legs',
    secondary_muscles: ['glutes', 'core'],
    equipment_required: ['Dumbbells'],
    exercise_type: 'compound',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Hold one dumbbell vertically at chest level.', 'Squat deep, keeping chest up.', 'Drive through heels to stand.'],
    common_mistakes: ['Not squatting deep enough.', 'Letting dumbbell pull chest forward.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 90,
    calories_per_set: 22,
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    slug: 'leg-press',
    muscle_group: 'legs',
    secondary_muscles: ['glutes', 'hamstrings'],
    equipment_required: ['Leg Press Machine'],
    exercise_type: 'compound',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Sit with feet hip-width on platform.', 'Lower until knees are at 90°.', 'Push through heels to full extension.'],
    common_mistakes: ['Knees caving inward.', 'Locking out at the top.'],
    default_sets: 4,
    default_reps: '10-15',
    rest_time_seconds: 90,
    calories_per_set: 25,
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    slug: 'leg-extension',
    muscle_group: 'legs',
    secondary_muscles: [],
    equipment_required: ['Leg Extension Machine'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Sit with pad on lower shin.', 'Extend legs until fully straightened.', 'Lower slowly with control.'],
    common_mistakes: ['Using momentum.', 'Not controlling eccentric.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 75,
    calories_per_set: 14,
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    slug: 'romanian-deadlift',
    muscle_group: 'hamstrings',
    secondary_muscles: ['lower_back', 'glutes'],
    equipment_required: ['Dumbbells'],
    exercise_type: 'compound',
    difficulty: 'intermediate',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Hold dumbbells in front of thighs.', 'Hinge at hips, feel a stretch in hamstrings.', 'Drive hips forward to return.'],
    common_mistakes: ['Rounding the back.', 'Squatting instead of hinging.'],
    default_sets: 3,
    default_reps: '10-12',
    rest_time_seconds: 90,
    calories_per_set: 20,
  },
  {
    id: 'dumbbell-lunge',
    name: 'Dumbbell Walking Lunge',
    slug: 'dumbbell-walking-lunge',
    muscle_group: 'legs',
    secondary_muscles: ['glutes', 'core'],
    equipment_required: ['Dumbbells'],
    exercise_type: 'compound',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Stand with dumbbells at sides.', 'Step forward, lower rear knee toward floor.', 'Push through front heel and alternate legs.'],
    common_mistakes: ['Knee extending past toes.', 'Leaning torso forward.'],
    default_sets: 3,
    default_reps: '10-12 each',
    rest_time_seconds: 90,
    calories_per_set: 20,
  },
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    slug: 'bodyweight-squat',
    muscle_group: 'legs',
    secondary_muscles: ['glutes', 'core'],
    equipment_required: [],
    exercise_type: 'bodyweight',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Feet shoulder-width, toes out slightly.', 'Squat until thighs are parallel.', 'Stand back up through heels.'],
    common_mistakes: ['Knees caving inward.', 'Not reaching depth.'],
    default_sets: 3,
    default_reps: '15-20',
    rest_time_seconds: 60,
    calories_per_set: 14,
  },
  // BICEPS
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    slug: 'barbell-curl',
    muscle_group: 'biceps',
    secondary_muscles: ['forearms'],
    equipment_required: ['Barbell', 'Weight Plates'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Stand with underhand shoulder-width grip.', 'Curl bar to shoulder level, upper arms fixed.', 'Lower with control.'],
    common_mistakes: ['Swinging body.', 'Not lowering to full extension.'],
    default_sets: 3,
    default_reps: '10-12',
    rest_time_seconds: 75,
    calories_per_set: 13,
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Bicep Curl',
    slug: 'dumbbell-bicep-curl',
    muscle_group: 'biceps',
    secondary_muscles: ['forearms'],
    equipment_required: ['Dumbbells'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Curl dumbbells to shoulder height.', 'Rotate palms up at top.', 'Lower slowly with control.'],
    common_mistakes: ['Swinging elbows forward.', 'Not supinating at top.'],
    default_sets: 3,
    default_reps: '10-12',
    rest_time_seconds: 75,
    calories_per_set: 12,
  },
  // TRICEPS
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    slug: 'overhead-tricep-extension',
    muscle_group: 'triceps',
    secondary_muscles: [],
    equipment_required: ['Dumbbells'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Hold one dumbbell with both hands above head.', 'Lower behind head by bending elbows.', 'Extend arms back up, squeezing triceps.'],
    common_mistakes: ['Flaring elbows out.', 'Moving upper arms.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 75,
    calories_per_set: 13,
  },
  {
    id: 'tricep-dip',
    name: 'Tricep Dip',
    slug: 'tricep-dip',
    muscle_group: 'triceps',
    secondary_muscles: ['chest', 'front_deltoid'],
    equipment_required: ['Dip Bars'],
    exercise_type: 'bodyweight',
    difficulty: 'intermediate',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Grip parallel bars, body upright.', 'Lower until upper arm is parallel to floor.', 'Press back up to full extension.'],
    common_mistakes: ['Leaning too far forward.', 'Not going to full depth.'],
    default_sets: 3,
    default_reps: '8-12',
    rest_time_seconds: 75,
    calories_per_set: 14,
  },
  // CORE
  {
    id: 'plank',
    name: 'Plank',
    slug: 'plank',
    muscle_group: 'core',
    secondary_muscles: ['shoulders', 'glutes'],
    equipment_required: [],
    exercise_type: 'bodyweight',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Forearms on floor, body in a straight line.', 'Engage core and hold the position.'],
    common_mistakes: ['Hips sagging.', 'Holding breath.'],
    default_sets: 3,
    default_reps: '30-60s',
    rest_time_seconds: 60,
    calories_per_set: 10,
  },
  // GLUTES
  {
    id: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    slug: 'barbell-hip-thrust',
    muscle_group: 'glutes',
    secondary_muscles: ['hamstrings', 'core'],
    equipment_required: ['Barbell', 'Weight Plates', 'Flat Bench'],
    exercise_type: 'compound',
    difficulty: 'intermediate',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Upper back against bench, barbell across hip crease.', 'Drive hips up until torso is straight.', 'Squeeze glutes at top, lower under control.'],
    common_mistakes: ['Hyperextending lower back.', 'Not achieving full hip extension.'],
    default_sets: 4,
    default_reps: '10-15',
    rest_time_seconds: 90,
    calories_per_set: 22,
  },

  // ─── V-TAPER PROGRAM ADDITIONS ───────────────────────────────────────
  // CHEST – isolation
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    slug: 'cable-fly',
    muscle_group: 'chest',
    secondary_muscles: ['front_deltoid'],
    equipment_required: ['Cable Machine'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Set cables at shoulder height, grip handles.', 'Step forward into a split stance.', 'Bring hands together in a wide arc in front of chest.', 'Slowly return to starting position.'],
    common_mistakes: ['Bending elbows too much.', 'Using momentum.', 'Incomplete range of motion.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 60,
    calories_per_set: 13,
  },

  // SHOULDERS – compound
  {
    id: 'barbell-overhead-press',
    name: 'Barbell Overhead Press',
    slug: 'barbell-overhead-press',
    muscle_group: 'shoulders',
    secondary_muscles: ['triceps', 'upper_traps', 'core'],
    equipment_required: ['Barbell', 'Weight Plates'],
    exercise_type: 'compound',
    difficulty: 'intermediate',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Stand with barbell at upper chest, overhand grip slightly wider than shoulders.', 'Press bar straight overhead until arms are locked out.', 'Lower bar back to upper chest under control.'],
    common_mistakes: ['Leaning back excessively.', 'Flaring elbows forward.', 'Not locking out at top.'],
    default_sets: 4,
    default_reps: '8-10',
    rest_time_seconds: 90,
    calories_per_set: 20,
  },

  // SHOULDERS – isolation (rear delts)
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    slug: 'rear-delt-fly',
    muscle_group: 'shoulders',
    secondary_muscles: ['upper_back', 'traps'],
    equipment_required: ['Dumbbells'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Hinge forward at hips 45–90°, arms hanging down.', 'Raise dumbbells out to the sides in a wide arc.', 'Squeeze rear delts at top, lower slowly.'],
    common_mistakes: ['Using too much weight.', 'Shrugging traps.', 'Not hinging enough.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 45,
    calories_per_set: 10,
  },

  // TRICEPS – isolation
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    slug: 'tricep-pushdown',
    muscle_group: 'triceps',
    secondary_muscles: [],
    equipment_required: ['Cable Machine'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Stand at cable machine, grip bar overhand at chest height.', 'Keep elbows pinned to sides.', 'Push bar down until arms are fully extended.', 'Slowly return to starting position.'],
    common_mistakes: ['Flaring elbows.', 'Leaning forward excessively.', 'Using body weight to push.'],
    default_sets: 3,
    default_reps: '10-15',
    rest_time_seconds: 45,
    calories_per_set: 11,
  },

  // BACK / SHOULDERS – isolation
  {
    id: 'face-pull',
    name: 'Face Pull',
    slug: 'face-pull',
    muscle_group: 'shoulders',
    secondary_muscles: ['rear_deltoid', 'upper_back', 'biceps'],
    equipment_required: ['Cable Machine'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Set cable at head height with rope attachment.', 'Pull rope toward your face, separating hands.', 'Finish with hands beside ears, elbows flared.', 'Return slowly to full extension.'],
    common_mistakes: ['Pulling too low.', 'Not separating hands at end.', 'Using momentum.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 45,
    calories_per_set: 10,
  },

  // BICEPS – isolation
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    slug: 'hammer-curl',
    muscle_group: 'biceps',
    secondary_muscles: ['forearms', 'brachialis'],
    equipment_required: ['Dumbbells'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Hold dumbbells with neutral grip (palms facing each other).', 'Curl both dumbbells toward shoulders keeping palms neutral.', 'Squeeze brachialis at top, lower slowly.'],
    common_mistakes: ['Swinging body.', 'Rotating wrists.', 'Not reaching full extension.'],
    default_sets: 3,
    default_reps: '10-12',
    rest_time_seconds: 45,
    calories_per_set: 11,
  },

  // HAMSTRINGS – isolation
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    slug: 'leg-curl',
    muscle_group: 'hamstrings',
    secondary_muscles: ['glutes'],
    equipment_required: ['Leg Curl Machine'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Lie face down on machine, align knees with the pivot point.', 'Curl legs toward glutes, squeezing hamstrings.', 'Lower with control to full extension.'],
    common_mistakes: ['Lifting hips off pad.', 'Using momentum.', 'Not reaching full extension.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 45,
    calories_per_set: 13,
  },

  // CALVES – isolation
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    slug: 'calf-raise',
    muscle_group: 'legs',
    secondary_muscles: ['soleus'],
    equipment_required: ['Calf Raise Machine'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Position shoulders under pads, balls of feet on platform.', 'Rise on toes as high as possible.', 'Hold 1 second at top, lower heels below platform level.'],
    common_mistakes: ['Bouncing at the bottom.', 'Not achieving full range of motion.', 'Going too fast.'],
    default_sets: 4,
    default_reps: '15-20',
    rest_time_seconds: 30,
    calories_per_set: 10,
  },

  // CORE
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    slug: 'hanging-leg-raise',
    muscle_group: 'core',
    secondary_muscles: ['hip_flexors'],
    equipment_required: ['Pull-up Bar'],
    exercise_type: 'bodyweight',
    difficulty: 'intermediate',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Hang from pull-up bar with straight arms.', 'Raise legs straight until parallel to floor (or higher).', 'Lower with control without swinging.'],
    common_mistakes: ['Swinging body.', 'Bending knees excessively.', 'Using momentum.'],
    default_sets: 3,
    default_reps: '12-15',
    rest_time_seconds: 45,
    calories_per_set: 12,
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    slug: 'dead-bug',
    muscle_group: 'core',
    secondary_muscles: ['lower_back'],
    equipment_required: [],
    exercise_type: 'bodyweight',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Lie on back, arms reaching to ceiling, knees at 90°.', 'Lower opposite arm and leg toward floor simultaneously.', 'Return to start and repeat on other side.'],
    common_mistakes: ['Letting lower back arch off floor.', 'Moving too fast.', 'Holding breath.'],
    default_sets: 3,
    default_reps: '12 each side',
    rest_time_seconds: 45,
    calories_per_set: 8,
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    slug: 'cable-crunch',
    muscle_group: 'core',
    secondary_muscles: [],
    equipment_required: ['Cable Machine'],
    exercise_type: 'isolation',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Kneel facing cable machine, grip rope behind head.', 'Crunch down, pulling elbows toward knees.', 'Squeeze abs at bottom, slowly return to upright.'],
    common_mistakes: ['Using hip flexors to pull down.', 'Not focusing on ab contraction.', 'Going too heavy.'],
    default_sets: 3,
    default_reps: '15',
    rest_time_seconds: 45,
    calories_per_set: 10,
  },
  {
    id: 'vacuum-hold',
    name: 'Vacuum Hold',
    slug: 'vacuum-hold',
    muscle_group: 'core',
    secondary_muscles: [],
    equipment_required: [],
    exercise_type: 'bodyweight',
    difficulty: 'beginner',
    video_url: null,
    thumbnail_url: null,
    instructions: ['Exhale all air completely.', 'Pull navel toward spine as hard as possible.', 'Hold the contraction while breathing shallowly.'],
    common_mistakes: ['Holding breath incorrectly.', 'Not fully exhaling first.', 'Tensing abs instead of pulling in.'],
    default_sets: 3,
    default_reps: '30s',
    rest_time_seconds: 30,
    calories_per_set: 4,
  },
]
