import { Exercise } from '@/types'

export const ARM_EXERCISES: Exercise[] = [
  {
    id: 'barbell-curl', name: 'Barbell Curl', slug: 'barbell-curl',
    category: 'hypertrophy', primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'],
    movementPattern: 'vertical_pull', equipmentRequired: ['barbell'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['arm_size', 'aesthetic'],
    fatigueScore: 3, recoveryHours: 36, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Stand with barbell, underhand grip shoulder-width.', 'Curl bar up to shoulder level.', 'Lower slowly with full extension.'],
    tips: ['Keep elbows pinned to sides.', 'Squeeze at the top.'],
    mistakes: ['Swinging body.', 'Not going to full extension.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 60,
  },
  {
    id: 'dumbbell-curl', name: 'Dumbbell Curl', slug: 'dumbbell-curl',
    category: 'hypertrophy', primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'],
    movementPattern: 'vertical_pull', equipmentRequired: ['dumbbells'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['arm_size', 'aesthetic'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'weight',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand with dumbbells at sides, palms forward.', 'Curl up one or both arms.', 'Squeeze bicep at top, lower controlled.'],
    tips: ['Alternate arms for more focus.', 'Supinate wrist at top for peak contraction.'],
    mistakes: ['Using momentum.', 'Not controlling the negative.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 60,
  },
  {
    id: 'hammer-curl', name: 'Hammer Curl', slug: 'hammer-curl',
    category: 'hypertrophy', primaryMuscles: ['biceps'], secondaryMuscles: ['forearms'],
    movementPattern: 'vertical_pull', equipmentRequired: ['dumbbells'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['arm_size'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'weight',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Hold dumbbells with neutral grip (palms facing each other).', 'Curl up keeping neutral grip.', 'Lower controlled.'],
    tips: ['Targets brachialis for arm thickness.', 'Great for forearm development.'],
    mistakes: ['Flaring elbows out.', 'Swinging.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 60,
  },
  {
    id: 'skull-crushers', name: 'Skull Crushers', slug: 'skull-crushers',
    category: 'hypertrophy', primaryMuscles: ['triceps'], secondaryMuscles: [],
    movementPattern: 'vertical_push', equipmentRequired: ['barbell', 'bench'], equipmentOptional: ['dumbbells'],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['arm_size', 'aesthetic'],
    fatigueScore: 3, recoveryHours: 36, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Lie on bench, hold bar with narrow grip above chest.', 'Lower bar toward forehead by bending elbows.', 'Extend arms back to start.'],
    tips: ['Lower to behind head for more stretch.', 'Keep elbows pointed to ceiling.'],
    mistakes: ['Flaring elbows.', 'Too much weight compromising form.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 75,
  },
  {
    id: 'tricep-pushdown', name: 'Tricep Pushdown', slug: 'tricep-pushdown',
    category: 'hypertrophy', primaryMuscles: ['triceps'], secondaryMuscles: [],
    movementPattern: 'vertical_push', equipmentRequired: ['cable_machine'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['arm_size'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Set cable to high position with bar or rope.', 'Push down to full extension.', 'Control the return, keeping elbows pinned.'],
    tips: ['Use rope for better peak contraction.', 'Lean slightly forward.'],
    mistakes: ['Moving elbows away from body.', 'Using momentum.'],
    defaultSets: 3, defaultReps: '12-15', defaultRest: 45,
  },
  {
    id: 'dips', name: 'Dips', slug: 'dips',
    category: 'strength', primaryMuscles: ['triceps', 'chest'], secondaryMuscles: ['front_delts'],
    movementPattern: 'vertical_push', equipmentRequired: ['dip_bars'], equipmentOptional: [],
    isBodyweight: true, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['arm_size', 'mass_builder'],
    fatigueScore: 6, recoveryHours: 48, progressionType: 'reps',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Support yourself on parallel bars, arms locked.', 'Lower body by bending elbows to 90°.', 'Push back up to full lockout.'],
    tips: ['Lean forward for chest focus.', 'Stay upright for tricep focus.'],
    mistakes: ['Going too deep (shoulder strain).', 'Not locking out.'],
    defaultSets: 3, defaultReps: '8-12', defaultRest: 90,
  },
  {
    id: 'overhead-tricep-extension', name: 'Overhead Tricep Extension', slug: 'overhead-tricep-extension',
    category: 'hypertrophy', primaryMuscles: ['triceps'], secondaryMuscles: [],
    movementPattern: 'vertical_push', equipmentRequired: ['dumbbells'], equipmentOptional: ['cable_machine'],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['arm_size'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'weight',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Hold dumbbell overhead with both hands.', 'Lower behind head by bending elbows.', 'Extend arms back to start.'],
    tips: ['Keep elbows close to ears.', 'Great for long head of triceps.'],
    mistakes: ['Flaring elbows.', 'Using too much weight.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 60,
  },
  {
    id: 'concentration-curl', name: 'Concentration Curl', slug: 'concentration-curl',
    category: 'hypertrophy', primaryMuscles: ['biceps'], secondaryMuscles: [],
    movementPattern: 'vertical_pull', equipmentRequired: ['dumbbells'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['arm_size', 'aesthetic'],
    fatigueScore: 1, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Sit on bench, brace elbow against inner thigh.', 'Curl dumbbell up to shoulder.', 'Squeeze at top, lower slowly.'],
    tips: ['Isolates biceps perfectly.', 'Great for peak development.'],
    mistakes: ['Using body momentum.', 'Not bracing elbow properly.'],
    defaultSets: 3, defaultReps: '10-15', defaultRest: 45,
  },
]
