import { Exercise } from '@/types'

export const BACK_EXERCISES: Exercise[] = [
  {
    id: 'deadlift', name: 'Deadlift', slug: 'deadlift',
    category: 'strength', primaryMuscles: ['back', 'hamstrings'], secondaryMuscles: ['glutes', 'core', 'traps', 'forearms'],
    movementPattern: 'hinge', equipmentRequired: ['barbell'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['strength', 'muscle_gain'], physiqueTags: ['mass_builder', 'posterior_chain'],
    fatigueScore: 10, recoveryHours: 72, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Stand with feet hip-width, bar over mid-foot.', 'Hinge at hips, grip bar just outside knees.', 'Drive through floor, extending hips and knees together.'],
    tips: ['Keep bar close to body.', 'Think "push the floor away".'],
    mistakes: ['Rounding lower back.', 'Jerking the bar off floor.', 'Hyperextending at the top.'],
    defaultSets: 4, defaultReps: '5-8', defaultRest: 180,
  },
  {
    id: 'barbell-row', name: 'Barbell Row', slug: 'barbell-row',
    category: 'strength', primaryMuscles: ['back', 'lats'], secondaryMuscles: ['biceps', 'rear_delts', 'core'],
    movementPattern: 'horizontal_pull', equipmentRequired: ['barbell'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['mass_builder', 'v_taper'],
    fatigueScore: 7, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Hinge forward ~45°, grip bar shoulder-width.', 'Pull bar to lower chest/upper belly.', 'Squeeze shoulder blades at top, lower controlled.'],
    tips: ['Keep torso angle stable.', 'Pull with elbows, not hands.'],
    mistakes: ['Using momentum.', 'Standing too upright.', 'Rounding lower back.'],
    defaultSets: 4, defaultReps: '8-12', defaultRest: 120,
  },
  {
    id: 'pull-up', name: 'Pull-Up', slug: 'pull-up',
    category: 'strength', primaryMuscles: ['lats'], secondaryMuscles: ['biceps', 'rear_delts', 'core', 'forearms'],
    movementPattern: 'vertical_pull', equipmentRequired: ['pullup_bar'], equipmentOptional: [],
    isBodyweight: true, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'strength', 'athletic_performance'], physiqueTags: ['v_taper', 'lat_width', 'functional'],
    fatigueScore: 6, recoveryHours: 48, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Hang from bar with overhand grip, slightly wider than shoulders.', 'Pull up until chin clears bar.', 'Lower with control to full hang.'],
    tips: ['Initiate by depressing shoulder blades.', 'Avoid kipping.'],
    mistakes: ['Half reps.', 'Kipping or swinging.', 'Not reaching full extension at bottom.'],
    defaultSets: 4, defaultReps: '6-12', defaultRest: 120,
  },
  {
    id: 'lat-pulldown', name: 'Lat Pulldown', slug: 'lat-pulldown',
    category: 'hypertrophy', primaryMuscles: ['lats'], secondaryMuscles: ['biceps', 'rear_delts'],
    movementPattern: 'vertical_pull', equipmentRequired: ['lat_pulldown_machine'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain'], physiqueTags: ['v_taper', 'lat_width'],
    fatigueScore: 4, recoveryHours: 36, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Sit with thighs secured under pad.', 'Pull bar to upper chest with wide grip.', 'Control the return, feeling the lat stretch.'],
    tips: ['Lean back slightly.', 'Drive elbows down and back.'],
    mistakes: ['Pulling behind the neck.', 'Using momentum.', 'Gripping too tight.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 75,
  },
  {
    id: 'dumbbell-row', name: 'Dumbbell Row', slug: 'dumbbell-row',
    category: 'hypertrophy', primaryMuscles: ['back', 'lats'], secondaryMuscles: ['biceps', 'rear_delts'],
    movementPattern: 'horizontal_pull', equipmentRequired: ['dumbbells', 'bench'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['v_taper', 'aesthetic'],
    fatigueScore: 5, recoveryHours: 36, progressionType: 'weight',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Place one knee and hand on bench, other foot on floor.', 'Pull dumbbell to hip level.', 'Squeeze back at top, lower controlled.'],
    tips: ['Keep core braced and back flat.', 'Pull to hip, not chest.'],
    mistakes: ['Rotating torso.', 'Using momentum.', 'Shrugging shoulder.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 75,
  },
  {
    id: 'seated-cable-row', name: 'Seated Cable Row', slug: 'seated-cable-row',
    category: 'hypertrophy', primaryMuscles: ['back'], secondaryMuscles: ['biceps', 'rear_delts', 'lats'],
    movementPattern: 'horizontal_pull', equipmentRequired: ['cable_machine'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain'], physiqueTags: ['aesthetic'],
    fatigueScore: 4, recoveryHours: 36, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Sit with feet on pads, slight knee bend.', 'Pull handle to lower chest.', 'Squeeze shoulder blades, return controlled.'],
    tips: ['Keep chest up throughout.', 'Avoid leaning too far forward or back.'],
    mistakes: ['Rocking with momentum.', 'Rounding back.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 75,
  },
  {
    id: 'face-pull', name: 'Face Pull', slug: 'face-pull',
    category: 'hypertrophy', primaryMuscles: ['rear_delts'], secondaryMuscles: ['traps', 'back'],
    movementPattern: 'horizontal_pull', equipmentRequired: ['cable_machine'], equipmentOptional: ['resistance_bands'],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'athletic_performance'], physiqueTags: ['v_taper', 'shoulder_width', 'aesthetic'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Set cable at face height with rope attachment.', 'Pull rope to face, externally rotating at end.', 'Squeeze rear delts and hold.'],
    tips: ['Great for posture and shoulder health.', 'Can do daily as prehab.'],
    mistakes: ['Too heavy.', 'Not externally rotating.'],
    defaultSets: 3, defaultReps: '15-20', defaultRest: 45,
  },
  {
    id: 'inverted-row', name: 'Inverted Row', slug: 'inverted-row',
    category: 'strength', primaryMuscles: ['back'], secondaryMuscles: ['biceps', 'rear_delts', 'core'],
    movementPattern: 'horizontal_pull', equipmentRequired: [], equipmentOptional: ['pullup_bar'],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 4, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Set bar at waist height or use a table edge.', 'Hang underneath, body straight.', 'Pull chest to bar, squeeze back.'],
    tips: ['Elevate feet for harder variation.', 'Great pull-up progression.'],
    mistakes: ['Sagging hips.', 'Not full range of motion.'],
    defaultSets: 3, defaultReps: '8-15', defaultRest: 60,
  },
  {
    id: 'romanian-deadlift', name: 'Romanian Deadlift', slug: 'romanian-deadlift',
    category: 'strength', primaryMuscles: ['hamstrings'], secondaryMuscles: ['glutes', 'lower_back', 'back'],
    movementPattern: 'hinge', equipmentRequired: ['barbell'], equipmentOptional: ['dumbbells'],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['posterior_chain', 'glute_builder'],
    fatigueScore: 7, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Stand with bar at hip level.', 'Hinge at hips, pushing butt back, bar slides down thighs.', 'Feel hamstring stretch, then drive hips forward to stand.'],
    tips: ['Keep bar against legs.', 'Slight knee bend throughout.'],
    mistakes: ['Rounding the back.', 'Bending knees too much (turns into squat).'],
    defaultSets: 3, defaultReps: '8-12', defaultRest: 90,
  },
]
