import { Exercise } from '@/types'

export const CARDIO_EXERCISES: Exercise[] = [
  {
    id: 'jumping-jacks', name: 'Jumping Jacks', slug: 'jumping-jacks',
    category: 'cardio', primaryMuscles: ['full_body'], secondaryMuscles: ['shoulders', 'calves'],
    movementPattern: 'squat', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['fat_loss', 'athletic_performance'], physiqueTags: ['conditioning', 'fat_loss'],
    fatigueScore: 3, recoveryHours: 24, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand feet together, arms at sides.', 'Jump feet apart, raise arms overhead.', 'Jump back to start.'],
    tips: ['Land softly on balls of feet.', 'Keep pace consistent.'],
    mistakes: ['Landing on heels.', 'Not fully extending arms.'],
    defaultSets: 3, defaultReps: '30s', defaultRest: 20,
  },
  {
    id: 'mountain-climbers', name: 'Mountain Climbers', slug: 'mountain-climbers',
    category: 'cardio', primaryMuscles: ['core'], secondaryMuscles: ['shoulders', 'hip_flexors', 'quads'],
    movementPattern: 'carry', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['fat_loss', 'athletic_performance'], physiqueTags: ['conditioning', 'fat_loss', 'core_definition'],
    fatigueScore: 5, recoveryHours: 24, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Start in high plank.', 'Drive one knee toward chest rapidly.', 'Alternate legs at a running pace.'],
    tips: ['Keep hips level.', 'Drive knees fully to chest.'],
    mistakes: ['Hips rising too high.', 'Not keeping core tight.'],
    defaultSets: 3, defaultReps: '30s', defaultRest: 20,
  },
  {
    id: 'burpees', name: 'Burpees', slug: 'burpees',
    category: 'fat_loss', primaryMuscles: ['full_body'], secondaryMuscles: ['chest', 'quads', 'core', 'shoulders'],
    movementPattern: 'squat', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'intermediate', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['fat_loss', 'athletic_performance'], physiqueTags: ['conditioning', 'fat_loss'],
    fatigueScore: 8, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand, then squat and place hands on floor.', 'Jump feet back to plank, do a push-up.', 'Jump feet forward, jump up with arms overhead.'],
    tips: ['Scale by removing push-up or jump.', 'Focus on form over speed.'],
    mistakes: ['Skipping the push-up.', 'Not jumping fully.'],
    defaultSets: 3, defaultReps: '10', defaultRest: 30,
  },
  {
    id: 'high-knees', name: 'High Knees', slug: 'high-knees',
    category: 'cardio', primaryMuscles: ['quads', 'hip_flexors'], secondaryMuscles: ['core', 'calves'],
    movementPattern: 'squat', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['fat_loss', 'athletic_performance'], physiqueTags: ['conditioning', 'fat_loss'],
    fatigueScore: 4, recoveryHours: 24, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand tall, run in place.', 'Drive knees up to hip level.', 'Pump arms for momentum.'],
    tips: ['Stay on balls of feet.', 'Keep posture upright.'],
    mistakes: ['Leaning back.', 'Not lifting knees high enough.'],
    defaultSets: 3, defaultReps: '30s', defaultRest: 20,
  },
  {
    id: 'box-jumps', name: 'Box Jumps', slug: 'box-jumps',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['calves', 'core'],
    movementPattern: 'squat', equipmentRequired: ['plyo_box'], equipmentOptional: [],
    isBodyweight: true, difficulty: 'intermediate', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['athletic_performance', 'strength'], physiqueTags: ['functional', 'conditioning'],
    fatigueScore: 6, recoveryHours: 48, progressionType: 'reps',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Stand facing box, feet shoulder-width.', 'Swing arms and jump onto box.', 'Land softly, stand tall, step down.'],
    tips: ['Start with lower box.', 'Focus on soft landing.'],
    mistakes: ['Landing too hard.', 'Not using arm swing.'],
    defaultSets: 3, defaultReps: '8', defaultRest: 60,
  },
  {
    id: 'jump-squat', name: 'Jump Squat', slug: 'jump-squat',
    category: 'fat_loss', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['calves', 'core'],
    movementPattern: 'squat', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'intermediate', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['fat_loss', 'athletic_performance'], physiqueTags: ['conditioning', 'functional'],
    fatigueScore: 5, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Squat down to parallel.', 'Explode up jumping as high as possible.', 'Land softly, immediately go into next rep.'],
    tips: ['Absorb landing through legs.', 'Arms help generate power.'],
    mistakes: ['Landing with locked knees.', 'Not reaching full depth.'],
    defaultSets: 3, defaultReps: '12', defaultRest: 45,
  },
  {
    id: 'battle-ropes', name: 'Battle Ropes', slug: 'battle-ropes',
    category: 'fat_loss', primaryMuscles: ['shoulders', 'core'], secondaryMuscles: ['forearms', 'back'],
    movementPattern: 'carry', equipmentRequired: ['resistance_bands'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['fat_loss', 'athletic_performance'], physiqueTags: ['conditioning', 'fat_loss'],
    fatigueScore: 6, recoveryHours: 24, progressionType: 'duration',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Hold rope ends at hip level in half squat.', 'Alternate arms creating waves in rope.', 'Maintain rhythm for set duration.'],
    tips: ['Stay low in squat position.', 'Breathe rhythmically.'],
    mistakes: ['Standing too upright.', 'Only using arms.'],
    defaultSets: 3, defaultReps: '30s', defaultRest: 30,
  },
]
