import { Exercise } from '@/types'

export const CHEST_EXERCISES: Exercise[] = [
  {
    id: 'barbell-bench-press', name: 'Barbell Bench Press', slug: 'barbell-bench-press',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'front_delts'],
    movementPattern: 'horizontal_push', equipmentRequired: ['barbell', 'bench'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['mass_builder', 'aesthetic'],
    fatigueScore: 7, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Lie flat on bench, grip barbell slightly wider than shoulders.', 'Unrack and lower bar to mid-chest.', 'Press up explosively to lockout.'],
    tips: ['Retract shoulder blades for stability.', 'Drive feet into the floor.'],
    mistakes: ['Bouncing bar off chest.', 'Flaring elbows too wide.', 'Lifting hips off bench.'],
    defaultSets: 4, defaultReps: '8-12', defaultRest: 120,
  },
  {
    id: 'incline-dumbbell-press', name: 'Incline Dumbbell Press', slug: 'incline-dumbbell-press',
    category: 'hypertrophy', primaryMuscles: ['upper_chest'], secondaryMuscles: ['front_delts', 'triceps'],
    movementPattern: 'horizontal_push', equipmentRequired: ['dumbbells', 'incline_bench'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['upper_chest', 'v_taper', 'aesthetic'],
    fatigueScore: 6, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Set bench to 30-45 degrees.', 'Press dumbbells up from shoulder level.', 'Lower slowly with control.'],
    tips: ['Use 30° for more upper chest activation.', 'Touch dumbbells lightly at the top.'],
    mistakes: ['Setting bench too steep (becomes a shoulder press).', 'Not controlling the negative.'],
    defaultSets: 4, defaultReps: '8-12', defaultRest: 90,
  },
  {
    id: 'dumbbell-bench-press', name: 'Dumbbell Bench Press', slug: 'dumbbell-bench-press',
    category: 'hypertrophy', primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'front_delts'],
    movementPattern: 'horizontal_push', equipmentRequired: ['dumbbells', 'bench'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['aesthetic', 'mass_builder'],
    fatigueScore: 6, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Lie flat on bench with a dumbbell in each hand.', 'Press up to full extension.', 'Lower slowly to chest level.'],
    tips: ['Greater range of motion than barbell.', 'Good for fixing strength imbalances.'],
    mistakes: ['Dumbbells drifting too wide.', 'Not going deep enough.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 90,
  },
  {
    id: 'push-up', name: 'Push-Up', slug: 'push-up',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'front_delts', 'core'],
    movementPattern: 'horizontal_push', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'fat_loss', 'strength', 'athletic_performance'], physiqueTags: ['functional', 'aesthetic'],
    fatigueScore: 3, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Start in plank, hands shoulder-width.', 'Lower chest to floor.', 'Push back up to full extension.'],
    tips: ['Squeeze chest at the top.', 'Keep body in a straight line.'],
    mistakes: ['Sagging hips.', 'Flaring elbows past 45°.', 'Not reaching full depth.'],
    defaultSets: 3, defaultReps: '12-20', defaultRest: 60,
  },
  {
    id: 'chest-fly', name: 'Dumbbell Fly', slug: 'chest-fly',
    category: 'hypertrophy', primaryMuscles: ['chest'], secondaryMuscles: ['front_delts'],
    movementPattern: 'horizontal_push', equipmentRequired: ['dumbbells', 'bench'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['aesthetic'],
    fatigueScore: 3, recoveryHours: 36, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Lie flat, arms extended above chest with slight bend.', 'Open arms wide in an arc.', 'Squeeze chest to bring dumbbells back together.'],
    tips: ['Maintain slight elbow bend throughout.', 'Feel the stretch at the bottom.'],
    mistakes: ['Straightening arms completely.', 'Going too heavy.'],
    defaultSets: 3, defaultReps: '12-15', defaultRest: 60,
  },
  {
    id: 'cable-crossover', name: 'Cable Crossover', slug: 'cable-crossover',
    category: 'hypertrophy', primaryMuscles: ['chest'], secondaryMuscles: ['front_delts'],
    movementPattern: 'horizontal_push', equipmentRequired: ['cable_machine'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['aesthetic', 'core_definition'],
    fatigueScore: 3, recoveryHours: 36, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Set cables to high position.', 'Step forward, bring handles together in front of chest.', 'Control the return.'],
    tips: ['Cross hands slightly for peak contraction.', 'Lean forward slightly.'],
    mistakes: ['Using too much momentum.', 'Not controlling the eccentric.'],
    defaultSets: 3, defaultReps: '12-15', defaultRest: 60,
  },
  {
    id: 'chest-press-machine', name: 'Chest Press Machine', slug: 'chest-press-machine',
    category: 'hypertrophy', primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'front_delts'],
    movementPattern: 'horizontal_push', equipmentRequired: ['chest_press_machine'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain'], physiqueTags: ['mass_builder'],
    fatigueScore: 4, recoveryHours: 36, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Adjust seat so handles are at chest height.', 'Push forward to full extension.', 'Return slowly.'],
    tips: ['Great for beginners or burnout sets.', 'Focus on squeezing chest.'],
    mistakes: ['Seat too high or low.', 'Locking out elbows aggressively.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 75,
  },
  {
    id: 'diamond-push-up', name: 'Diamond Push-Up', slug: 'diamond-push-up',
    category: 'strength', primaryMuscles: ['chest'], secondaryMuscles: ['triceps', 'front_delts'],
    movementPattern: 'horizontal_push', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['arm_size', 'functional'],
    fatigueScore: 4, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Place hands together under chest forming a diamond.', 'Lower chest to hands.', 'Push back up, squeezing triceps.'],
    tips: ['Keep elbows close to body.', 'Great triceps builder.'],
    mistakes: ['Flaring elbows.', 'Sagging hips.'],
    defaultSets: 3, defaultReps: '10-15', defaultRest: 60,
  },
]
