import { Exercise } from '@/types'

export const CORE_EXERCISES: Exercise[] = [
  {
    id: 'plank', name: 'Plank', slug: 'plank',
    category: 'core', primaryMuscles: ['core'], secondaryMuscles: ['shoulders', 'glutes'],
    movementPattern: 'carry', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'fat_loss', 'strength', 'athletic_performance'], physiqueTags: ['core_definition', 'functional'],
    fatigueScore: 3, recoveryHours: 24, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Forearms on floor, body in straight line.', 'Brace core, squeeze glutes.', 'Hold position without sagging.'],
    tips: ['Breathe steadily.', 'Add weight on back to progress.'],
    mistakes: ['Hips sagging.', 'Hips too high.', 'Not breathing.'],
    defaultSets: 3, defaultReps: '30-60s', defaultRest: 45,
  },
  {
    id: 'hanging-leg-raise', name: 'Hanging Leg Raise', slug: 'hanging-leg-raise',
    category: 'core', primaryMuscles: ['core', 'hip_flexors'], secondaryMuscles: ['obliques', 'forearms'],
    movementPattern: 'rotation', equipmentRequired: ['pullup_bar'], equipmentOptional: [],
    isBodyweight: true, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['core_definition', 'v_taper'],
    fatigueScore: 4, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Hang from bar with straight arms.', 'Raise legs until parallel or higher.', 'Lower with control.'],
    tips: ['Straight legs for harder version.', 'Toes to bar for advanced.'],
    mistakes: ['Swinging.', 'Using momentum.', 'Only lifting knees halfway.'],
    defaultSets: 3, defaultReps: '10-15', defaultRest: 60,
  },
  {
    id: 'russian-twist', name: 'Russian Twist', slug: 'russian-twist',
    category: 'core', primaryMuscles: ['obliques', 'core'], secondaryMuscles: [],
    movementPattern: 'rotation', equipmentRequired: [], equipmentOptional: ['dumbbells'],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'fat_loss'], physiqueTags: ['core_definition'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Sit with knees bent, lean back 45°.', 'Rotate torso side to side.', 'Hold weight for added resistance.'],
    tips: ['Lift feet for harder variation.', 'Control the rotation.'],
    mistakes: ['Only moving arms.', 'Rounding back.'],
    defaultSets: 3, defaultReps: '20', defaultRest: 45,
  },
  {
    id: 'bicycle-crunch', name: 'Bicycle Crunch', slug: 'bicycle-crunch',
    category: 'core', primaryMuscles: ['core', 'obliques'], secondaryMuscles: ['hip_flexors'],
    movementPattern: 'rotation', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'fat_loss'], physiqueTags: ['core_definition'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Lie on back, hands behind head.', 'Bring opposite elbow to knee.', 'Alternate in a pedaling motion.'],
    tips: ['Slow and controlled beats fast.', 'Full rotation of torso.'],
    mistakes: ['Pulling on neck.', 'Going too fast.'],
    defaultSets: 3, defaultReps: '20', defaultRest: 45,
  },
  {
    id: 'side-plank', name: 'Side Plank', slug: 'side-plank',
    category: 'core', primaryMuscles: ['obliques', 'core'], secondaryMuscles: ['shoulders', 'glutes'],
    movementPattern: 'carry', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'athletic_performance'], physiqueTags: ['core_definition', 'functional'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Lie on side, prop on forearm.', 'Lift hips to form straight line.', 'Hold, then switch sides.'],
    tips: ['Stack feet or stagger for balance.', 'Add hip dips for more work.'],
    mistakes: ['Hips dropping.', 'Not stacking shoulder over elbow.'],
    defaultSets: 3, defaultReps: '30s each', defaultRest: 30,
  },
  {
    id: 'ab-wheel-rollout', name: 'Ab Wheel Rollout', slug: 'ab-wheel-rollout',
    category: 'core', primaryMuscles: ['core'], secondaryMuscles: ['shoulders', 'lower_back'],
    movementPattern: 'carry', equipmentRequired: ['ab_wheel'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['strength', 'muscle_gain'], physiqueTags: ['core_definition'],
    fatigueScore: 5, recoveryHours: 36, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Kneel with hands on ab wheel.', 'Roll forward extending body.', 'Pull back using core to starting position.'],
    tips: ['Start from knees before trying standing.', 'Brace core throughout.'],
    mistakes: ['Sagging hips.', 'Going too far too soon.'],
    defaultSets: 3, defaultReps: '8-12', defaultRest: 60,
  },
  {
    id: 'dead-bug', name: 'Dead Bug', slug: 'dead-bug',
    category: 'core', primaryMuscles: ['core'], secondaryMuscles: ['hip_flexors'],
    movementPattern: 'carry', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['athletic_performance', 'muscle_gain'], physiqueTags: ['core_definition', 'functional'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Lie on back, arms up, knees at 90°.', 'Extend opposite arm and leg.', 'Return and alternate.'],
    tips: ['Keep lower back pressed into floor.', 'Move slowly and controlled.'],
    mistakes: ['Arching lower back.', 'Holding breath.'],
    defaultSets: 3, defaultReps: '10 each', defaultRest: 30,
  },
]
