import { Exercise } from '@/types'

export const LEG_EXERCISES: Exercise[] = [
  {
    id: 'barbell-squat', name: 'Barbell Squat', slug: 'barbell-squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings', 'core', 'lower_back'],
    movementPattern: 'squat', equipmentRequired: ['barbell'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['strength', 'muscle_gain'], physiqueTags: ['mass_builder', 'quad_sweep'],
    fatigueScore: 9, recoveryHours: 72, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Bar on upper traps, feet shoulder-width.', 'Sit back and down, breaking at hips and knees.', 'Drive through feet to stand, chest up.'],
    tips: ['Brace core before each rep.', 'Knees track over toes.'],
    mistakes: ['Knees caving inward.', 'Leaning too far forward.', 'Not hitting depth.'],
    defaultSets: 4, defaultReps: '6-10', defaultRest: 180,
  },
  {
    id: 'goblet-squat', name: 'Goblet Squat', slug: 'goblet-squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['core'],
    movementPattern: 'squat', equipmentRequired: ['dumbbells'], equipmentOptional: ['kettlebell'],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength', 'fat_loss'], physiqueTags: ['functional', 'quad_sweep'],
    fatigueScore: 5, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Hold dumbbell vertically at chest.', 'Squat down between legs.', 'Drive up through heels.'],
    tips: ['Great squat pattern teacher.', 'Elbows push knees out at bottom.'],
    mistakes: ['Rounding back.', 'Heels lifting.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 75,
  },
  {
    id: 'leg-press', name: 'Leg Press', slug: 'leg-press',
    category: 'hypertrophy', primaryMuscles: ['quads'], secondaryMuscles: ['glutes', 'hamstrings'],
    movementPattern: 'squat', equipmentRequired: ['leg_press_machine'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain'], physiqueTags: ['quad_sweep', 'mass_builder'],
    fatigueScore: 6, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Sit in machine, feet shoulder-width on platform.', 'Lower platform by bending knees to 90°.', 'Press platform away to near-lockout.'],
    tips: ['Higher foot placement for more glute/ham.', 'Lower foot placement for quad focus.'],
    mistakes: ['Locking out knees fully.', 'Lifting butt off seat.'],
    defaultSets: 4, defaultReps: '10-15', defaultRest: 90,
  },
  {
    id: 'leg-extension', name: 'Leg Extension', slug: 'leg-extension',
    category: 'hypertrophy', primaryMuscles: ['quads'], secondaryMuscles: [],
    movementPattern: 'squat', equipmentRequired: ['leg_extension_machine'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['quad_sweep', 'aesthetic'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Sit in machine, pad against lower shins.', 'Extend legs fully.', 'Hold at top briefly, lower with control.'],
    tips: ['Pause at top for peak contraction.', 'Go lighter for higher reps.'],
    mistakes: ['Using momentum.', 'Not getting full extension.'],
    defaultSets: 3, defaultReps: '12-15', defaultRest: 60,
  },
  {
    id: 'leg-curl', name: 'Leg Curl', slug: 'leg-curl',
    category: 'hypertrophy', primaryMuscles: ['hamstrings'], secondaryMuscles: ['calves'],
    movementPattern: 'hinge', equipmentRequired: ['leg_curl_machine'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['posterior_chain', 'aesthetic'],
    fatigueScore: 2, recoveryHours: 36, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Lie face down, pad against lower calves.', 'Curl legs up toward glutes.', 'Lower controlled.'],
    tips: ['Point toes away for more hamstring.', 'Avoid lifting hips.'],
    mistakes: ['Using momentum.', 'Not full range of motion.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 60,
  },
  {
    id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', slug: 'bulgarian-split-squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings', 'core'],
    movementPattern: 'lunge', equipmentRequired: ['bench'], equipmentOptional: ['dumbbells'],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength', 'athletic_performance'], physiqueTags: ['glute_builder', 'functional'],
    fatigueScore: 7, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Place rear foot on bench behind you.', 'Lower until front thigh is parallel.', 'Drive through front heel to stand.'],
    tips: ['Lean forward slightly for more glute.', 'Stay upright for quad focus.'],
    mistakes: ['Knee past toes excessively.', 'Losing balance.'],
    defaultSets: 3, defaultReps: '10 each', defaultRest: 75,
  },
  {
    id: 'walking-lunge', name: 'Walking Lunge', slug: 'walking-lunge',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['hamstrings', 'core'],
    movementPattern: 'lunge', equipmentRequired: [], equipmentOptional: ['dumbbells'],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'fat_loss', 'athletic_performance'], physiqueTags: ['glute_builder', 'functional', 'conditioning'],
    fatigueScore: 5, recoveryHours: 48, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Take a large step forward.', 'Lower until both knees are at 90°.', 'Drive through front foot to step forward with the other leg.'],
    tips: ['Keep torso upright.', 'Add dumbbells for more challenge.'],
    mistakes: ['Steps too short.', 'Knee extending past toes.'],
    defaultSets: 3, defaultReps: '12 each', defaultRest: 60,
  },
  {
    id: 'bodyweight-squat', name: 'Bodyweight Squat', slug: 'bodyweight-squat',
    category: 'strength', primaryMuscles: ['quads', 'glutes'], secondaryMuscles: ['core', 'hamstrings'],
    movementPattern: 'squat', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'upper_lower', 'full_body'],
    goals: ['fat_loss', 'athletic_performance', 'muscle_gain'], physiqueTags: ['functional', 'conditioning'],
    fatigueScore: 3, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand with feet shoulder-width.', 'Sit back and down to parallel or below.', 'Drive up through heels.'],
    tips: ['Arms forward for balance.', 'Keep chest up.'],
    mistakes: ['Knees caving in.', 'Heels lifting.'],
    defaultSets: 3, defaultReps: '15-20', defaultRest: 45,
  },
  {
    id: 'hip-thrust', name: 'Hip Thrust', slug: 'hip-thrust',
    category: 'hypertrophy', primaryMuscles: ['glutes'], secondaryMuscles: ['hamstrings', 'core'],
    movementPattern: 'hinge', equipmentRequired: ['bench'], equipmentOptional: ['barbell', 'dumbbells'],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'athletic_performance'], physiqueTags: ['glute_builder', 'aesthetic'],
    fatigueScore: 5, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Upper back on bench, feet flat on floor.', 'Drive hips up until body forms a straight line.', 'Squeeze glutes at top, lower controlled.'],
    tips: ['Chin tucked to avoid arching back.', 'Pause at top for 1 second.'],
    mistakes: ['Hyperextending lower back.', 'Feet too close to bench.'],
    defaultSets: 3, defaultReps: '10-12', defaultRest: 75,
  },
  {
    id: 'calf-raise', name: 'Standing Calf Raise', slug: 'calf-raise',
    category: 'hypertrophy', primaryMuscles: ['calves'], secondaryMuscles: [],
    movementPattern: 'squat', equipmentRequired: [], equipmentOptional: ['calf_raise_machine', 'dumbbells'],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain'], physiqueTags: ['aesthetic'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand on edge of step, heels hanging off.', 'Rise up on toes as high as possible.', 'Lower heels below step for full stretch.'],
    tips: ['Pause at top for 2 seconds.', 'Slow negatives build more muscle.'],
    mistakes: ['Bouncing at bottom.', 'Not using full range.'],
    defaultSets: 4, defaultReps: '15-20', defaultRest: 45,
  },
]
