import { Exercise } from '@/types'

export const SHOULDER_EXERCISES: Exercise[] = [
  {
    id: 'overhead-press', name: 'Overhead Press', slug: 'overhead-press',
    category: 'strength', primaryMuscles: ['shoulders', 'front_delts'], secondaryMuscles: ['triceps', 'core', 'traps'],
    movementPattern: 'vertical_push', equipmentRequired: ['barbell'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['strength', 'muscle_gain'], physiqueTags: ['shoulder_width', 'mass_builder'],
    fatigueScore: 7, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Grip bar at shoulder width, bar resting on front delts.', 'Press bar overhead to full lockout.', 'Lower back to shoulders with control.'],
    tips: ['Brace core tightly.', 'Move head out of the way as bar passes face.'],
    mistakes: ['Leaning back excessively.', 'Not locking out.', 'Flaring ribs.'],
    defaultSets: 4, defaultReps: '6-10', defaultRest: 120,
  },
  {
    id: 'dumbbell-shoulder-press', name: 'Dumbbell Shoulder Press', slug: 'dumbbell-shoulder-press',
    category: 'hypertrophy', primaryMuscles: ['shoulders', 'front_delts'], secondaryMuscles: ['triceps'],
    movementPattern: 'vertical_push', equipmentRequired: ['dumbbells'], equipmentOptional: ['bench'],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain', 'strength'], physiqueTags: ['shoulder_width', 'aesthetic'],
    fatigueScore: 5, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Sit or stand with dumbbells at shoulder height.', 'Press up to full extension.', 'Lower back to shoulder level.'],
    tips: ['Seated version is stricter.', 'Palms forward or neutral grip both work.'],
    mistakes: ['Using momentum.', 'Not reaching full lockout.'],
    defaultSets: 4, defaultReps: '8-12', defaultRest: 90,
  },
  {
    id: 'dumbbell-lateral-raise', name: 'Dumbbell Lateral Raise', slug: 'dumbbell-lateral-raise',
    category: 'hypertrophy', primaryMuscles: ['side_delts'], secondaryMuscles: ['traps'],
    movementPattern: 'rotation', equipmentRequired: ['dumbbells'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain'], physiqueTags: ['shoulder_width', 'v_taper', 'aesthetic'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand with dumbbells at sides.', 'Raise arms out to sides until parallel with floor.', 'Lower slowly with control.'],
    tips: ['Slight forward lean targets side delts better.', 'Think "pour water from a pitcher".'],
    mistakes: ['Going too heavy.', 'Using momentum.', 'Raising above shoulder level.'],
    defaultSets: 4, defaultReps: '12-20', defaultRest: 45,
  },
  {
    id: 'cable-lateral-raise', name: 'Cable Lateral Raise', slug: 'cable-lateral-raise',
    category: 'hypertrophy', primaryMuscles: ['side_delts'], secondaryMuscles: ['traps'],
    movementPattern: 'rotation', equipmentRequired: ['cable_machine'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'physique'],
    goals: ['muscle_gain'], physiqueTags: ['shoulder_width', 'v_taper', 'aesthetic'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: false, gymFriendly: true,
    instructions: ['Set cable to lowest position.', 'Stand sideways, grab handle with far hand.', 'Raise arm to side until parallel.'],
    tips: ['Constant tension throughout range of motion.', 'Superior to dumbbells for hypertrophy.'],
    mistakes: ['Using too much weight.', 'Bending elbow excessively.'],
    defaultSets: 3, defaultReps: '12-15', defaultRest: 45,
  },
  {
    id: 'rear-delt-fly', name: 'Rear Delt Fly', slug: 'rear-delt-fly',
    category: 'hypertrophy', primaryMuscles: ['rear_delts'], secondaryMuscles: ['traps', 'back'],
    movementPattern: 'horizontal_pull', equipmentRequired: ['dumbbells'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['muscle_gain'], physiqueTags: ['aesthetic', 'shoulder_width'],
    fatigueScore: 2, recoveryHours: 24, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Bend forward 45° at hips.', 'Raise dumbbells out to sides, leading with elbows.', 'Squeeze rear delts at top.'],
    tips: ['Keep arms slightly bent.', 'Control the negative.'],
    mistakes: ['Swinging body.', 'Using traps instead of rear delts.'],
    defaultSets: 3, defaultReps: '12-15', defaultRest: 45,
  },
  {
    id: 'pike-push-up', name: 'Pike Push-Up', slug: 'pike-push-up',
    category: 'strength', primaryMuscles: ['shoulders', 'front_delts'], secondaryMuscles: ['triceps', 'core'],
    movementPattern: 'vertical_push', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body'],
    goals: ['strength', 'muscle_gain'], physiqueTags: ['shoulder_width', 'functional'],
    fatigueScore: 5, recoveryHours: 36, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Start in downward-dog position, hips high.', 'Bend elbows and lower head toward floor.', 'Push back up to start.'],
    tips: ['Elevate feet for harder variation.', 'Progression toward handstand push-up.'],
    mistakes: ['Not keeping hips high.', 'Flaring elbows wide.'],
    defaultSets: 3, defaultReps: '8-12', defaultRest: 60,
  },
  {
    id: 'arnold-press', name: 'Arnold Press', slug: 'arnold-press',
    category: 'hypertrophy', primaryMuscles: ['shoulders', 'front_delts', 'side_delts'], secondaryMuscles: ['triceps'],
    movementPattern: 'vertical_push', equipmentRequired: ['dumbbells'], equipmentOptional: ['bench'],
    isBodyweight: false, difficulty: 'intermediate', compatibleSplits: ['ppl', 'bro_split', 'upper_lower'],
    goals: ['muscle_gain'], physiqueTags: ['shoulder_width', 'aesthetic'],
    fatigueScore: 5, recoveryHours: 48, progressionType: 'weight',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Start with dumbbells at chin level, palms facing you.', 'Rotate palms outward while pressing overhead.', 'Reverse the motion on the way down.'],
    tips: ['Smooth rotation throughout press.', 'Hits all three delt heads.'],
    mistakes: ['Rushing the rotation.', 'Not getting full range of motion.'],
    defaultSets: 3, defaultReps: '8-12', defaultRest: 75,
  },
]
