import { Exercise } from '@/types'

export const WARMUP_COOLDOWN_EXERCISES: Exercise[] = [
  // ─── WARMUP / MOBILITY ──────────────────────────────────────────────
  {
    id: 'arm-circles', name: 'Arm Circles', slug: 'arm-circles',
    category: 'warmup', primaryMuscles: ['shoulders'], secondaryMuscles: ['traps'],
    movementPattern: 'rotation', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'fat_loss', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 1, recoveryHours: 0, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Extend arms to sides.', 'Make small circles, gradually increasing.', 'Reverse direction.'],
    tips: ['Good for warming up shoulders before pressing.'], mistakes: ['Going too fast.'],
    defaultSets: 2, defaultReps: '30s', defaultRest: 10,
  },
  {
    id: 'leg-swings', name: 'Leg Swings', slug: 'leg-swings',
    category: 'warmup', primaryMuscles: ['hip_flexors'], secondaryMuscles: ['glutes', 'hamstrings'],
    movementPattern: 'hinge', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'fat_loss', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 1, recoveryHours: 0, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Hold wall for balance.', 'Swing leg forward and back in controlled arc.', 'Switch legs.'],
    tips: ['Gradually increase range of motion.'], mistakes: ['Swinging too aggressively.'],
    defaultSets: 2, defaultReps: '15 each', defaultRest: 10,
  },
  {
    id: 'cat-cow-stretch', name: 'Cat-Cow Stretch', slug: 'cat-cow-stretch',
    category: 'warmup', primaryMuscles: ['core', 'lower_back'], secondaryMuscles: ['shoulders'],
    movementPattern: 'rotation', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'fat_loss', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 1, recoveryHours: 0, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['On all fours, wrists under shoulders.', 'Arch back, lift head (cow).', 'Round back, tuck chin (cat).'],
    tips: ['Sync with breathing.'], mistakes: ['Moving too quickly.'],
    defaultSets: 2, defaultReps: '10', defaultRest: 10,
  },
  {
    id: 'inchworm', name: 'Inchworm', slug: 'inchworm',
    category: 'warmup', primaryMuscles: ['core', 'shoulders'], secondaryMuscles: ['hamstrings', 'chest'],
    movementPattern: 'hinge', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['fat_loss', 'athletic_performance'], physiqueTags: ['functional', 'conditioning'],
    fatigueScore: 2, recoveryHours: 0, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand tall, hinge forward to floor.', 'Walk hands out to plank.', 'Walk hands back, stand up.'],
    tips: ['Keep legs as straight as possible.'], mistakes: ['Bending knees too much.'],
    defaultSets: 2, defaultReps: '8', defaultRest: 15,
  },
  {
    id: 'band-pull-apart', name: 'Band Pull-Apart', slug: 'band-pull-apart',
    category: 'warmup', primaryMuscles: ['rear_delts'], secondaryMuscles: ['traps', 'back'],
    movementPattern: 'horizontal_pull', equipmentRequired: ['resistance_bands'], equipmentOptional: [],
    isBodyweight: false, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'strength', 'athletic_performance'], physiqueTags: ['functional', 'v_taper'],
    fatigueScore: 1, recoveryHours: 0, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Hold band at shoulder width.', 'Pull apart by squeezing shoulder blades.', 'Return slowly.'],
    tips: ['Great prehab for shoulders.'], mistakes: ['Shrugging shoulders.'],
    defaultSets: 2, defaultReps: '15', defaultRest: 15,
  },
  {
    id: 'hip-circles', name: 'Hip Circles', slug: 'hip-circles',
    category: 'warmup', primaryMuscles: ['hip_flexors', 'glutes'], secondaryMuscles: ['core'],
    movementPattern: 'rotation', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'fat_loss', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 1, recoveryHours: 0, progressionType: 'reps',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand on one leg.', 'Rotate hip in large circles.', 'Reverse direction, switch legs.'],
    tips: ['Great before squat/leg day.'], mistakes: ['Rushing through reps.'],
    defaultSets: 2, defaultReps: '10 each', defaultRest: 10,
  },

  // ─── COOLDOWN / FLEXIBILITY ─────────────────────────────────────────
  {
    id: 'standing-quad-stretch', name: 'Standing Quad Stretch', slug: 'standing-quad-stretch',
    category: 'mobility', primaryMuscles: ['quads'], secondaryMuscles: ['hip_flexors'],
    movementPattern: 'lunge', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'fat_loss', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 0, recoveryHours: 0, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand on one leg, grab opposite ankle.', 'Pull heel to glutes.', 'Hold 30s, switch.'],
    tips: ['Use wall for balance.'], mistakes: ['Arching lower back.'],
    defaultSets: 1, defaultReps: '30s each', defaultRest: 5,
  },
  {
    id: 'hamstring-stretch', name: 'Standing Hamstring Stretch', slug: 'hamstring-stretch',
    category: 'mobility', primaryMuscles: ['hamstrings'], secondaryMuscles: ['lower_back', 'calves'],
    movementPattern: 'hinge', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'fat_loss', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 0, recoveryHours: 0, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Extend one leg forward, heel on floor.', 'Hinge at hips, reach toward toes.', 'Hold 30s, switch.'],
    tips: ['Keep back flat.'], mistakes: ['Rounding upper back.', 'Bouncing.'],
    defaultSets: 1, defaultReps: '30s each', defaultRest: 5,
  },
  {
    id: 'childs-pose', name: 'Child\'s Pose', slug: 'childs-pose',
    category: 'mobility', primaryMuscles: ['lower_back'], secondaryMuscles: ['shoulders', 'hip_flexors'],
    movementPattern: 'hinge', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'fat_loss', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 0, recoveryHours: 0, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Kneel, sit back on heels.', 'Extend arms forward on floor.', 'Relax and hold 45-60s.'],
    tips: ['Great post-workout cooldown.'], mistakes: ['Not relaxing fully.'],
    defaultSets: 1, defaultReps: '45s', defaultRest: 5,
  },
  {
    id: 'chest-doorway-stretch', name: 'Chest Doorway Stretch', slug: 'chest-doorway-stretch',
    category: 'mobility', primaryMuscles: ['chest'], secondaryMuscles: ['front_delts'],
    movementPattern: 'horizontal_push', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 0, recoveryHours: 0, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Stand in doorway, forearms on frame at 90°.', 'Lean forward until chest stretch.', 'Hold 30s.'],
    tips: ['Great after push workouts.'], mistakes: ['Shrugging shoulders.'],
    defaultSets: 1, defaultReps: '30s', defaultRest: 5,
  },
  {
    id: 'pigeon-pose', name: 'Pigeon Pose', slug: 'pigeon-pose',
    category: 'mobility', primaryMuscles: ['glutes', 'hip_flexors'], secondaryMuscles: ['lower_back'],
    movementPattern: 'lunge', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'fat_loss', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 0, recoveryHours: 0, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['From plank, bring knee behind wrist.', 'Extend opposite leg straight behind.', 'Lower hips, hold 30s each side.'],
    tips: ['Best after leg day.'], mistakes: ['Hips not square.'],
    defaultSets: 1, defaultReps: '30s each', defaultRest: 5,
  },
  {
    id: 'shoulder-cross-body-stretch', name: 'Shoulder Cross-Body Stretch', slug: 'shoulder-cross-body-stretch',
    category: 'mobility', primaryMuscles: ['rear_delts', 'shoulders'], secondaryMuscles: [],
    movementPattern: 'horizontal_pull', equipmentRequired: [], equipmentOptional: [],
    isBodyweight: true, difficulty: 'beginner', compatibleSplits: ['ppl', 'bro_split', 'upper_lower', 'full_body', 'physique'],
    goals: ['muscle_gain', 'strength', 'athletic_performance'], physiqueTags: ['functional'],
    fatigueScore: 0, recoveryHours: 0, progressionType: 'duration',
    homeFriendly: true, gymFriendly: true,
    instructions: ['Bring one arm across chest.', 'Use other hand to pull closer.', 'Hold 30s, switch.'],
    tips: ['Great after pull or push workouts.'], mistakes: ['Pulling too aggressively.'],
    defaultSets: 1, defaultReps: '30s each', defaultRest: 5,
  },
]
